# Window Decorations
hide_window_decorations yes
font_family JetBrainsMono Nerd Font Regular
background #191919
foreground #d9d7d6
selection_background #252525
selection_foreground #d9d7d6
cursor #d9d7d6
