config_version = 14

[bar.default]
background_opacity = 0.89999997988343239
border = "error"
capsule_border = "surface_variant"
capsule_fill = "on_tertiary"
capsule_foreground = "outline"
capsule_thickness = 0.50999999232590199
center = [ "active_window" ]
end = [ "mangowm-keymode", "tray", "cpu", "sysmon", "notifications", "volume", "control-center" ]
font_family = "Maple Mono"
font_weight = 700
hover_highlight = false
margin_edge = 3
margin_ends = 500
padding = 11
radius = 73
scale = 0.90000000596046448
shadow = false
start = [ "workspaces", "clock", "media" ]
thickness = 33
widget_spacing = 10

[calendar]
enabled = true

[control_center.calendar]
show_events_card = false

[desktop_widgets]
enabled = false

[dock]
background_opacity = 0.99999997764825821

[location]
address = "lahore"
auto_locate = true

[lockscreen]
blur_intensity = 0.17999999597668648
fingerprint = false
tint_intensity = 0.25999999418854713

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [ "lockscreen-login-box@HDMI-A-1", "lockscreen-widget-0000000000000001" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 720.0
    cx = 960.0
    cy = 826.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface"
        background_opacity = 1.0
        background_radius = 5.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 5.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = false
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 48.0
    box_width = 192.0
    cx = 960.0
    cy = 644.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        background_opacity = 1.0
        background_padding = 0
        background_radius = 6
        center_text = true
        clock_style = "digital"
        format = "{:%I:%M %p}"

[plugins]
enabled = [ "gambled23/mangowm-keymode" ]

[shell]
app_icon_color = "error"
app_icon_colorize = true
avatar_path = "/home/huraira/Pictures/pfps i like/79788381.png"
font_family = "Maple Mono ExtraBold"
polkit_agent = true
settings_show_advanced = true
time_format = "{:%I:%M %p}"

    [shell.greeter_sync]
    privilege_command = "foot -e pkexec"

    [shell.panel]
    floating_offset = 3
    open_near_click_control_center = true

[system.monitor]
gpu_poll_seconds = 2

[theme]
builtin = "Noctalia"
community_palette = "Monochrome"
mode = "dark"
source = "community"
wallpaper_scheme = "soft"

    [theme.templates]
    community_ids = [ "obsidian", "heroiclauncher", "prismlauncher" ]

[wallpaper]
directory = "/home/huraira/Pictures/wallpapers"
transition_on_startup = true

    [wallpaper.default]
    path = "/home/huraira/Pictures/wallpapers/wallhaven-6kv9ww_1920x1080 (1).png"

    [wallpaper.last]
    path = "/home/huraira/Pictures/wallpapers/wallhaven-6kv9ww_1920x1080 (1).png"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/huraira/Pictures/wallpapers/wallhaven-6kv9ww_1920x1080 (1).png"

    [[wallpaper.favorite]]
    community_palette = "Monochrome"
    palette_source = "community"
    path = "/home/huraira/Pictures/wallpapers/wallhaven-6kv9ww_1920x1080 (1).png"
    theme_mode = "dark"

[widget.active_window]
anchor = true
color = "error"
display = "text_only"
max_length = 221
title_scroll = "on_hover"

[widget.clock]
color = "tertiary"
enabled = true
format = "{:%I:%M %p}"

[widget.control-center]
color = "error"
custom_image = "/home/huraira/Pictures/CachyOS.webp"
custom_image_colorize = true
icon_color = "error"
scale = 1.1500000000000001

[widget.cpu]
color = "error"
highlight_color = "secondary"
scale = 1.1000000000000001
show_label = false
show_value = false

[widget.mangowm-keymode]
color = "surface_variant"
icon_color = "on_tertiary"
scale = 0.20000000000000001
show_text = false
type = "gambled23/mangowm-keymode:mangowm-keymode"

[widget.media]
art_size = 19
hide_artist = true
hide_when_no_media = true
max_length = 151
title_scroll = "on_hover"

[widget.notifications]
color = "error"

[widget.session]
color = "tertiary"
custom_image = "/usr/share/noctalia/assets/images/distros/cachy.svg"
custom_image_colorize = true
icon_color = "tertiary"
scale = 1.1500000000000001

[widget.sysmon]
color = "error"
highlight_color = "secondary"
scale = 1.05
show_value = false
stat = "cpu_temp"

[widget.tray]
color = "error"
drawer = true
drawer_item_size = 15.0
scale = 0.75

[widget.volume]
color = "error"
mute_color = "secondary"
scale = 1.05
show_label = false

[widget.workspaces]
active_pill_size = 2.4500000000000002
empty_color = "primary"
focused_color = "error"
hide_when_empty = true
inactive_pill_size = 1.05
occupied_color = "error"
pill_scale = 0.80000000000000004
scale = 0.94999999999999996